export const GET_ANNOUNCEMENTS =  'GET_ANNOUNCEMENTS';
export const ADD_ANNOUNCEMENT =  'ADD_ANNOUNCEMENT';
export const DELETE_ANNOUNCEMENT =  'DELETE_ANNOUNCEMENT';
export const ANNOUNCEMENTS_LOADING =  'NNOUNCEMENTS_LOADING';
